[build]
  command = "nuxt build"
  publish = ".output/public"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[build.environment]
  NITRO_PRESET = "netlify"
  PNPM_FLAGS = "--shamefully-hoist"
  NODE_VERSION = "20"
